export const EVALUATOR_SET_NAME = "EVALUATOR_SET_NAME";
export const EVALUATOR_SET_TITLE = "EVALUATOR_SET_TITLE";
export const EVALUATOR_SET_PROFESSION = "EVALUATOR_SET_PROFESSION";
export const EVALUATOR_SET_ORGANISATION = "EVALUATOR_SET_ORGANISATION";