const PLAYER_CHOOSE_DECK = "PLAYER_CHOOSE_DECK";
export const PLAYER_CHOOSE_DECK_A = `${PLAYER_CHOOSE_DECK}_A`;
export const PLAYER_CHOOSE_DECK_B = `${PLAYER_CHOOSE_DECK}_B`;
export const PLAYER_CHOOSE_DECK_C = `${PLAYER_CHOOSE_DECK}_C`;
export const PLAYER_CHOOSE_DECK_D = `${PLAYER_CHOOSE_DECK}_D`;